require_remote_outside_brazil: true

brazil_location_keywords:
  - brasil
  - brazil
  - são paulo
  - sao paulo
  - sp
  - rio de janeiro
  - rj
  - belo horizonte
  - bh
  - minas gerais
  - mg
  - curitiba
  - pr
  - porto alegre
  - rs
  - florianópolis
  - florianopolis
  - sc
  - salvador
  - ba
  - recife
  - pe
  - fortaleza
  - ce
  - brasília
  - brasilia
  - df
  - campinas
  - santos
  - sorocaba
  - osasco
  - barueri

remote_keywords:
  - remote
  - fully remote
  - 100% remote
  - work from home
  - wfh
  - anywhere
  - distributed
  - worldwide
  - global
  - home office
  - remoto
  - 100% remoto
  - trabalho remoto
  - remote-first
  - remote first

# Anti-ruído: só deixa passar Director/Head/VP/SVP se tiver um desses termos NO TÍTULO
must_contain_any_of:
  - finance
  - financial
  - accounting
  - controllership
  - controller
  - controlling
  - tax
  - treasury
  - fp&a
  - fiscal
  - tribut
  - impostos
  - contab
  - controladoria
  - tesouraria

target_title_keywords:
  - cfo
  - chief financial officer
  - diretor financeiro
  - diretora financeira
  - finance director
  - director of finance
  - head of finance
  - vp finance
  - vp of finance
  - vice president finance
  - svp finance
  - svp of finance
  - senior vice president finance

  - accounting director
  - director of accounting
  - head of accounting
  - controllership director
  - director of controllership
  - head of controllership
  - controller
  - financial controller
  - diretor de controladoria
  - diretora de controladoria
  - diretor de contabilidade
  - diretora de contabilidade

  - accounting and


